"""ANN 전용 BL 실험 configs.

원본 bl_config.py 가 팀원에 의해 변경된 후 분리 — pull 후 import 시 사용.
"""
from bl_config import BASELINE  # 같은 baseline 사용

ANN_EXPERIMENTS = [
    {**BASELINE, 'name': 'paper_lstm', 'p_mode': 'lstm_predicted',
            'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'paper_ann', 'p_mode': 'ann_predicted',
            'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_mcap_eq_fpm_pap',     'p_mode': 'lstm_predicted', 'p_weight': 'eq', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_mcap_rp_fpm_pap',     'p_mode': 'lstm_predicted', 'p_weight': 'rp', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_mcap_eq_fpm_pap_ann', 'p_mode': 'ann_predicted',  'p_weight': 'eq', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_mcap_rp_fpm_pap_ann', 'p_mode': 'ann_predicted',  'p_weight': 'rp', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_eq_mcap_fpm_pap',     'p_mode': 'lstm_predicted', 'prior': 'capm_eq', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_rp_mcap_fpm_pap',     'p_mode': 'lstm_predicted', 'prior': 'capm_rp', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_eq_mcap_fpm_pap_ann', 'p_mode': 'ann_predicted',  'prior': 'capm_eq', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_rp_mcap_fpm_pap_ann', 'p_mode': 'ann_predicted',  'prior': 'capm_rp', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_mcap_mcap_fpm_he',     'p_mode': 'lstm_predicted', 'p_weight': 'mcap', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'he_litterman'},
    {**BASELINE, 'name': 'mat_mcap_mcap_fpm_rms',    'p_mode': 'lstm_predicted', 'p_weight': 'mcap', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'rmse'},
    {**BASELINE, 'name': 'mat_mcap_mcap_fpm_he_ann', 'p_mode': 'ann_predicted',  'p_weight': 'mcap', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'he_litterman'},
    {**BASELINE, 'name': 'mat_mcap_mcap_fpm_rms_ann','p_mode': 'ann_predicted',  'p_weight': 'mcap', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'rmse'},
    {**BASELINE, 'name': 'mat_mcap_eq_fix_pap_ann',  'p_mode': 'ann_predicted', 'p_weight': 'eq', 'q_mode': 'fixed',      'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_mcap_eq_inv_pap_ann',  'p_mode': 'ann_predicted', 'p_weight': 'eq', 'q_mode': 'inv_lambda', 'omega_mode': 'ff3_paper', 'lam_mean': 2.5},
    {**BASELINE, 'name': 'mat_mcap_eq_vsp_pap_ann',  'p_mode': 'ann_predicted', 'p_weight': 'eq', 'q_mode': 'vol_spread', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_mcap_rp_fix_pap_ann',  'p_mode': 'ann_predicted', 'p_weight': 'rp', 'q_mode': 'fixed',      'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_mcap_rp_lam_pap_ann',  'p_mode': 'ann_predicted', 'p_weight': 'rp', 'q_mode': 'lambda',     'omega_mode': 'ff3_paper', 'lam_mean': 2.5},
    {**BASELINE, 'name': 'mat_mcap_rp_inv_pap_ann',  'p_mode': 'ann_predicted', 'p_weight': 'rp', 'q_mode': 'inv_lambda', 'omega_mode': 'ff3_paper', 'lam_mean': 2.5},
    {**BASELINE, 'name': 'mat_mcap_rp_vsp_pap_ann',  'p_mode': 'ann_predicted', 'p_weight': 'rp', 'q_mode': 'vol_spread', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_eq_mcap_fix_pap_ann',  'p_mode': 'ann_predicted', 'prior': 'capm_eq', 'p_weight': 'mcap', 'q_mode': 'fixed',      'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_eq_mcap_lam_pap_ann',  'p_mode': 'ann_predicted', 'prior': 'capm_eq', 'p_weight': 'mcap', 'q_mode': 'lambda',     'omega_mode': 'ff3_paper', 'lam_mean': 2.5},
    {**BASELINE, 'name': 'mat_eq_mcap_raw_pap_ann',  'p_mode': 'ann_predicted', 'prior': 'capm_eq', 'p_weight': 'mcap', 'q_mode': 'raw_lam',    'omega_mode': 'ff3_paper', 'lam_mean': 2.5},
    {**BASELINE, 'name': 'mat_eq_mcap_inv_pap_ann',  'p_mode': 'ann_predicted', 'prior': 'capm_eq', 'p_weight': 'mcap', 'q_mode': 'inv_lambda', 'omega_mode': 'ff3_paper', 'lam_mean': 2.5},
    {**BASELINE, 'name': 'mat_eq_mcap_vsp_pap_ann',  'p_mode': 'ann_predicted', 'prior': 'capm_eq', 'p_weight': 'mcap', 'q_mode': 'vol_spread', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_rp_mcap_fix_pap_ann',  'p_mode': 'ann_predicted', 'prior': 'capm_rp', 'p_weight': 'mcap', 'q_mode': 'fixed',      'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_rp_mcap_lam_pap_ann',  'p_mode': 'ann_predicted', 'prior': 'capm_rp', 'p_weight': 'mcap', 'q_mode': 'lambda',     'omega_mode': 'ff3_paper', 'lam_mean': 2.5},
    {**BASELINE, 'name': 'mat_rp_mcap_raw_pap_ann',  'p_mode': 'ann_predicted', 'prior': 'capm_rp', 'p_weight': 'mcap', 'q_mode': 'raw_lam',    'omega_mode': 'ff3_paper', 'lam_mean': 2.5},
    {**BASELINE, 'name': 'mat_rp_mcap_inv_pap_ann',  'p_mode': 'ann_predicted', 'prior': 'capm_rp', 'p_weight': 'mcap', 'q_mode': 'inv_lambda', 'omega_mode': 'ff3_paper', 'lam_mean': 2.5},
    {**BASELINE, 'name': 'mat_rp_mcap_vsp_pap_ann',  'p_mode': 'ann_predicted', 'prior': 'capm_rp', 'p_weight': 'mcap', 'q_mode': 'vol_spread', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_eq_eq_inv_pap_ann',  'p_mode': 'ann_predicted',  'prior': 'capm_eq', 'p_weight': 'eq', 'q_mode': 'inv_lambda',    'omega_mode': 'ff3_paper', 'lam_mean': 2.5},
    {**BASELINE, 'name': 'mat_eq_eq_fpm_pap',      'p_mode': 'lstm_predicted', 'prior': 'capm_eq', 'p_weight': 'eq', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_eq_eq_fpm_pap_ann',  'p_mode': 'ann_predicted',  'prior': 'capm_eq', 'p_weight': 'eq', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_rp_eq_fpm_pap',      'p_mode': 'lstm_predicted', 'prior': 'capm_rp', 'p_weight': 'eq', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_rp_eq_fpm_pap_ann',  'p_mode': 'ann_predicted',  'prior': 'capm_rp', 'p_weight': 'eq', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_eq_rp_fix_pap_ann',  'p_mode': 'ann_predicted',  'prior': 'capm_eq', 'p_weight': 'rp', 'q_mode': 'fixed',          'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_eq_rp_lam_pap_ann',  'p_mode': 'ann_predicted',  'prior': 'capm_eq', 'p_weight': 'rp', 'q_mode': 'lambda',         'omega_mode': 'ff3_paper', 'lam_mean': 2.5},
    {**BASELINE, 'name': 'mat_eq_rp_inv_pap_ann',  'p_mode': 'ann_predicted',  'prior': 'capm_eq', 'p_weight': 'rp', 'q_mode': 'inv_lambda',     'omega_mode': 'ff3_paper', 'lam_mean': 2.5},
    {**BASELINE, 'name': 'mat_eq_rp_vsp_pap_ann',  'p_mode': 'ann_predicted',  'prior': 'capm_eq', 'p_weight': 'rp', 'q_mode': 'vol_spread',     'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_eq_rp_fpm_pap',      'p_mode': 'lstm_predicted', 'prior': 'capm_eq', 'p_weight': 'rp', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_eq_rp_fpm_pap_ann',  'p_mode': 'ann_predicted',  'prior': 'capm_eq', 'p_weight': 'rp', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_rp_rp_inv_pap_ann',  'p_mode': 'ann_predicted',  'prior': 'capm_rp', 'p_weight': 'rp', 'q_mode': 'inv_lambda',     'omega_mode': 'ff3_paper', 'lam_mean': 2.5},
    {**BASELINE, 'name': 'mat_rp_rp_fpm_pap',      'p_mode': 'lstm_predicted', 'prior': 'capm_rp', 'p_weight': 'rp', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_rp_rp_fpm_pap_ann',  'p_mode': 'ann_predicted',  'prior': 'capm_rp', 'p_weight': 'rp', 'q_mode': 'ff3_paper_mean', 'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_mcap_mcap_fix_pap_ann', 'p_mode': 'ann_predicted', 'p_weight': 'mcap', 'q_mode': 'fixed',      'omega_mode': 'ff3_paper'},
    {**BASELINE, 'name': 'mat_mcap_mcap_lam_pap_ann', 'p_mode': 'ann_predicted', 'p_weight': 'mcap', 'q_mode': 'lambda',     'omega_mode': 'ff3_paper', 'lam_mean': 2.5},
    {**BASELINE, 'name': 'mat_mcap_mcap_raw_pap_ann', 'p_mode': 'ann_predicted', 'p_weight': 'mcap', 'q_mode': 'raw_lam',    'omega_mode': 'ff3_paper', 'lam_mean': 2.5},
    {**BASELINE, 'name': 'mat_mcap_mcap_inv_pap_ann', 'p_mode': 'ann_predicted', 'p_weight': 'mcap', 'q_mode': 'inv_lambda', 'omega_mode': 'ff3_paper', 'lam_mean': 2.5},
    {**BASELINE, 'name': 'mat_mcap_mcap_vsp_pap_ann', 'p_mode': 'ann_predicted', 'p_weight': 'mcap', 'q_mode': 'vol_spread', 'omega_mode': 'ff3_paper'},
]
